version: 1.0.{build}
image: Visual Studio 2017
install:
- cmd: git submodule update --init --recursive
build_script:
- cmd: build.bat
test:
  assemblies:
    only:
    - '*.Test.dll'
artifacts:
- &1302144259 path: Release\Any CPU\net461\*
  &949611523 name: net461
- path: bin\Release\Any CPU\netcoreapp2.0\*
  name: netcoreapp2.0