version: {build}
image: Visual Studio 2017
install:
- cmd: git submodule update --init --recursive
build_script:
- cmd: build.bat
artifacts:
- &1302144259 path: bin\Release\Any CPU\net461\*
  &949611523 name: net461
- path: bin\Release\Any CPU\netcoreapp2.0\*
  name: netcoreapp2.0