version: 1.0.{build}
image: Visual Studio 2017
install:
- cmd: git submodule update --init --recursive
build_script:
- cmd: build.bat
test_script:
- cmd: runtests.bat
artifacts:
- path: bin\*.zip
  name: zip
- path: netcoreapp.binlog
  name: netcoreapp.binlog
- path: net461.binlog
  name: net461.binlog
deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: todo
  auth_token:
    secure: xE+f8rczPCfechI3U6gncyX2HWWVXN96l6RQ+XlVrWo+0YKf32phrXSzQ6WYEGEs
  artifact: zip
  draft: true
  prerelease: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
notifications:
- provider: Email
  to:
  - greenzest@gmail.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true